[package]
name = "clean-uc3m"
version = "1.0.0"
entrypoint = "lib.typ"
authors = ["Jorge Lázaro Ruiz", "Roland Schätzle <@roland-KA>"]
license = "MIT"
description = "A Typst Template for UC3M (Universidad Carlos III de Madrid) based on clean-dhbw"
repository = "https://github.com/jorgeygari/clean-uc3m-typst-template"
keywords = ["uc3m", "thesis", "universidad", "carlos", "madrid"]
categories = ["paper", "thesis", "report"]
exclude = ["template/main.pdf", "template/*.pdf"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"